@startuml
'https://plantuml.com/sequence-diagram

actor zcm
participant oppService
participant jobData

title 新增商机

loop 选择营业执照
zcm -> jobData : 选择营业执照
jobData -> zcm : 返回行业
end
|||

zcm -> oppService : 新增商机（新增industry_source参数）
oppService -> oppService : 新增商机（更新industry_source）

|||

zcm -> jobData : 根据行业+city获取有奖职位
jobData -> zcm : 返回有奖职位
@enduml