@startuml
'https://plantuml.com/sequence-diagram

actor zcm
participant oppService
participant jobData

title:获取商机详情

zcm->oppService:获取商机详情
oppService->zcm: 补充industry_source字段返回
note left : industry_source为1时行业置灰不可修改

zcm -> jobData : 根据 行业 + city 获取有奖职位
jobData -> zcm : 返回有奖职位列表

newpage 更新商机详情

loop 选择营业执照
zcm -> lead : 选择营业执照
lead -> jobData : 根据营业执照匹配行业
jobData -> lead : 返回行业
lead -> zcm : 返回行业
end

@enduml