@startuml
'https://plantuml.com/class-diagram'

actor OA
participant rateLimitfilter
participant wconfig
database redis
database mysql
participant crm_pc




OA -> rateLimitfilter: 访问,请求过滤
rateLimitfilter -> wconfig: 查询配置判断是否需要限流
|||
alt 不需要限流
    wconfig --> rateLimitfilter: 不需要限流
    rateLimitfilter --> OA: 不限流，放行
else 配置需要限流
    rateLimitfilter -> redis: incr该OA访问次数（设置ttl）
    redis --> rateLimitfilter: 返回该OA访问次数
    rateLimitfilter -> mysql: 访问次数入库
    |||
    ==是否放行==
    alt 访问次数超过阈值
        rateLimitfilter --> OA: 限流
    else 访问次数未超过阈值
        rateLimitfilter -> crm_pc: 不限流，放行
    end
end
|||

@enduml