server:
  port: 8080

stock-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # nacos实现的自定义权重负载均衡

ribbon:
  eager-load:
    enabled: true # 开启负载均衡的预加载
    clients: stock-service # 预加载的服务名

feign:
  client:
    config:
      stock-service:
        connectTimeout: 5000  # 设置feign的连接超时时间
        readTimeout: 5000 # 设置feign的请求超时时间
        loggerLevel: DEBUG # 设置feign的日志级别
        requestInterceptors: # 设置feign的请求拦截器
          - com.example.filter.FeignFilter
